### ISSUE TITLE
Update user authentication message

### ISSUE THREAD

**Issue by cthalmann** [osuosl/climesync#98]
If someone without proper credentials tries to update a user, they should receive a message stating that they need to log in.

Right now, it gives this error: https://pastebin.osuosl.org/41171/
and quits the program.

**Comment by subnomo** [comment]
Not just when updating users, either. If you're logged out and try to do anything other than sign in / connect, you get this error:

```
Traceback (most recent call last):
  File "./climesync.py", line 215, in <module>
    main()
  File "./climesync.py", line 212, in main
    interactive_mode()
  File "./climesync.py", line 149, in interactive_mode
    while menu():
  File "./climesync.py", line 136, in menu
    util.print_pretty(command())
  File "/home/sub/Work/climesync/climesync/commands.py", line 46, in wrapped_command
    if util.check_token_expiration(ts):
  File "/home/sub/Work/climesync/climesync/util.py", line 83, in check_token_expiration
    if ts and not ts.test and ts.token_expiration_time() <= datetime.now():
TypeError: can't compare datetime.datetime to dict
```
